### ISSUE TITLE
Add option to enable/disable the spell checking by default

### ISSUE THREAD

**Issue by wapsi** [fluks/fin-spell#7]
Please add an option to enable (or disable) the spell checking by default. Now I have to click on the Finnish flag icon in the toolbar and click "Päälle". It would be really nice if there was an option to enable or disable the spell checking by default.

Or even better: If there was a possiblity to add different sites (by using regex for example) where the spell checking is enabled or disabled by default, depending of the setting I suggested above.

**Comment by fluks** [comment]
What do you think if we have an option for always enabled and a blacklist or always disabled and a whitelist? So having both.

**Comment by wapsi** [comment]
Yeah, that sounds very good!

**Comment by fluks** [comment]
Okay, I did this. Now you need to refresh the page if you change the setting. Is it a problem? It can't be changed with the current implementation. I used contentScripts API, it made things easy.

**Comment by fluks** [comment]
Were you able to run the add-on in the development environment? I could push the commits and you could test them there.

I pushed enabled-disabled branch for testing.

**Comment by wapsi** [comment]
Yes, I was able to run and build the extension by using the sources I grabbed from here (git, enabled-disabled branch).

> Now you need to refresh the page if you change the setting. Is it a problem?

To be honest, I think this is a problem because if I want to turn the spell checking on/off **temporarily** from the flag icon it does not turn on/off it immediately: so the worst scenario is that I have to refresh the page and I will lose all the text I've written...

Maybe I revert what I said earlier: Is it possible to use the Always Disabled / Always Enabled feature as the permanent setting and in addition to that there is possiblity to turn off/on the spell checking temporarily from the flag icon (and maybe from the context menu in the future https://github.com/fluks/fin-spell/issues/8) and it disables/enables the spell checking immediately for the active tab only?

**Comment by fluks** [comment]
> Maybe I revert what I said earlier: Is it possible to use the Always Disabled / Always Enabled feature as the permanent setting and in addition to that there is possiblity to turn off/on the spell checking temporarily from the flag icon (and maybe from the context menu in the future #8) and it disables/enables the spell checking immediately for the active tab only?

Yes, I can do that, I think.

**Comment by fluks** [comment]
In the latest commit in the development branch, the functionality is now that the options control spell checking globally and you can temporarily enable or disable spell checking in the active tab. Refreshing the tab restores the global setting. Does it now work as you would like?

**Comment by wapsi** [comment]
Yes, now it feels very good! Thanks.

**Comment by wapsi** [comment]
I think this issue / feature request can be closed if you want to? I can confirm that this functionality is added and tested, thanks!
