### ISSUE TITLE
Add Päälle/Pois functionality in Firefox context menu

### ISSUE THREAD

**Issue by wapsi** [fluks/fin-spell#8]
Add Päälle/Pois functionality in Firefox context menu. Now I need to push the Finnish flag (extenstion) button and select Päälle or Pois to enable or disable the spell checking. It would be easier if this option was available in the Firefox context menu (the menu which opens when I right click ~anywhere on the website):

[X] Finnish Spell Checking

Firefox allows to edit the context menu from the addons, here is some documentation about it: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Context_menu_items

**Comment by fluks** [comment]
Should the context menu switch apply only on the current tab or be a global switch?

**Comment by wapsi** [comment]
Hmm, good question. Personally I would prefer to set it on globally as long as the user switch it back to off.

And I think this could be partly linked to my another feature request: https://github.com/fluks/fin-spell/issues/7 If that persistent setting is set to ON then this should set the ON/OFF globally as well.

**Comment by fluks** [comment]
So, the action bar (toolbar) and the context menu switches would do the same action, globally switch between always disabled or enabled? I'll try to implement this then.

**Comment by wapsi** [comment]
Yeah, exactly.

**Comment by fluks** [comment]
I added the context menu item in the enabled-disabled branch if you want to test it.

**Comment by wapsi** [comment]
Yeah, I tested this and it works, thanks!

BTW: Just a minor UIX thing: Is it possible to implement the context menu entry without a submenu? Maybe it can achieved by using menu entry with content: "Fin Spell: Set semporarily On" / "Fin Spell: Set semporarily Off" (depending what setting is currently set) directly on the root context menu:
![fin-spell-mockup1](https://user-images.githubusercontent.com/11405096/105876463-af7a5680-6007-11eb-9c66-e474945a8e35.png)

**Comment by wapsi** [comment]
And another thing: If toggle the spelling temporarily off (either from the context menu or by clicking the Finnish flag icon) it removes all the highlightings immediately but if I turn it back on it does not trigger the spell checking immediately: I have to change the text (put one space for example at the end) and after that it highlights the mispelled words.

Is it possible to trigger the spell checking for the whole text immediately the spell checking is turned on (temporarily)?

**Comment by fluks** [comment]
> Yeah, I tested this and it works, thanks!
> 
> BTW: Just a minor UIX thing: Is it possible to implement the context menu entry without a submenu? Maybe it can achieved by using menu entry with content: "Fin Spell: Set semporarily On" / "Fin Spell: Set semporarily Off" (depending what setting is currently set) directly on the root context menu:
> ![fin-spell-mockup1](https://user-images.githubusercontent.com/11405096/105876463-af7a5680-6007-11eb-9c66-e474945a8e35.png)

It's possible.

**Comment by fluks** [comment]
> And another thing: If toggle the spelling temporarily off (either from the context menu or by clicking the Finnish flag icon) it removes all the highlightings immediately but if I turn it back on it does not trigger the spell checking immediately: I have to change the text (put one space for example at the end) and after that it highlights the mispelled words.
> 
> Is it possible to trigger the spell checking for the whole text immediately the spell checking is turned on (temporarily)?

And this is possible too. Probably a simple call to highlight all the inputs.

**Comment by fluks** [comment]
> > And another thing: If toggle the spelling temporarily off (either from the context menu or by clicking the Finnish flag icon) it removes all the highlightings immediately but if I turn it back on it does not trigger the spell checking immediately: I have to change the text (put one space for example at the end) and after that it highlights the mispelled words.
> > Is it possible to trigger the spell checking for the whole text immediately the spell checking is turned on (temporarily)?
> 
> And this is possible too. Probably a simple call to highlight all the inputs.

Added in the newest commit. All the input elements are spell checked on page load and if you temporarily enable spell checking. The last input element has the focus, this probably needs fixing. And the last word in input elements are not spell checked. I guess when the element gets focused and the cursor is placed in the end and the last word is considered as the current word you are typing.

**Comment by fluks** [comment]
Now in the latest commit, on off context menu item should be shown without a sub-menu when possible.

**Comment by wapsi** [comment]
Yes, thanks! It's perfect!

I think this issue / feature request can be closed if you want to? I can confirm that this functionality is added and tested, thanks!
